# SAM CLI Configuration file
# Run 'sam deploy' to use these defaults

version = 0.1

[default.deploy.parameters]
stack_name = "cloud-compliance-canvas-backend"
resolve_s3 = true
s3_prefix = "cloud-compliance-canvas"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"production\" AllowedOrigins=\"*\""
